# Configuration file for running Domino platform locally

[airflow]
AIRFLOW_API_SERVER_PORT_HOST = 8080

[airflow_db]
AIRFLOW_DB_IMAGE = "ghcr.io/cloudnative-pg/postgresql"
AIRFLOW_DB_IMAGE_TAG = "13"
AIRFLOW_DB_HOST = "airflow-postgresql"
AIRFLOW_DB_PORT = 5432
AIRFLOW_DB_USER = "airflow"
AIRFLOW_DB_PASSWORD = "airflow"
AIRFLOW_DB_NAME = "postgres"

[path]
DOMINO_LOCAL_RUNNING_PATH = ""

[kind]
DOMINO_KIND_CLUSTER_NAME = "domino-cluster"
HTTP_PORT_HOST = 80
HTTPS_PORT_HOST = 443

[github]
DOMINO_GITHUB_WORKFLOWS_REPOSITORY = ""
DOMINO_DEFAULT_PIECES_REPOSITORY_TOKEN = ""
DOMINO_GITHUB_ACCESS_TOKEN_WORKFLOWS = ""
DOMINO_GITHUB_WORKFLOWS_SSH_PRIVATE_KEY = ""
DOMINO_GITHUB_WORKFLOWS_SSH_PUBLIC_KEY = ""

[domino_db]
DOMINO_CREATE_DATABASE = true # Changing to false will use the existing database defined by below variables
DOMINO_DB_HOST = "postgres"
DOMINO_DB_PORT = "postgres"
DOMINO_DB_USER = "postgres"
DOMINO_DB_PASSWORD = "postgres"
DOMINO_DB_NAME = "postgres"
DOMINO_CREATE_DEFAULT_USER = true

[domino_frontend]
API_URL = "http://localhost:80/api"

[dev]
DOMINO_LOCAL_DOMINO_PACKAGE=""