"""added awpl column

Revision ID: eb478b6619b0
Revises: a9f4cd2e4f57
Create Date: 2026-02-03 09:28:01.659080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb478b6619b0'
down_revision = 'a9f4cd2e4f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('awpl', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'awpl')
    # ### end Alembic commands ###
