name: Build and publish Domino Airflow production images

on:
  push:
    branches:
      - main
    paths:
      - domino/**
  # workflow_run:
  #   workflows:
  #     - "Build and publish domino-py package"
  #   branches:
  #     - main
  #   types:
  #     - completed

jobs:
  domino-airflow-base:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Domino Airflow Base Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Domino Airflow Base Prod
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/tauffer-consulting/domino-airflow-base:latest
          context: .
          file: Dockerfile-airflow-domino-base-dev # TODO check file to use in prod env, by now using the same as dev

  domino-pod-base:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Domino Base Pod Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Domino POD Base Prod
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/tauffer-consulting/domino-airflow-pod:latest
          context: .
          file: Dockerfile-airflow-domino-pod-dev # TODO check file to use in prod env, by now using the same as dev

  domino-pod-gpu-base:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Domino Base Pod GPU Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Domino POD Base Dev
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/tauffer-consulting/domino-airflow-pod:gpu
          context: .
          file: Dockerfile-airflow-domino-pod-gpu

  domino-storage-sidecar:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Domino Storage Sidecar Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/tauffer-consulting/domino-shared-storage-sidecar:latest
          context: domino/custom_operators/sidecar
          file: domino/custom_operators/sidecar/Dockerfile
