name: Build and publish Domino Airflow development images

on:
  push:
    branches:
      - dev
    paths:
      - src/domino/**

jobs:
  domino-airflow-base:
    name: Domino Airflow Base Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Domino Airflow Base image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/tauffer-consulting/domino-airflow-base-dev:latest
          context: .
          file: Dockerfile-airflow-domino-base-dev # TODO check file to use in prod env, by now using the same as dev

  domino-pod-base:
    name: Domino Base Pod Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Domino POD Base image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/tauffer-consulting/domino-airflow-pod-dev:latest
          context: .
          file: Dockerfile-airflow-domino-pod-dev # TODO check file to use in prod env, by now using the same as dev

  domino-pod-gpu-base:
    name: Domino Base Pod GPU Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Domino POD Base image with GPU support
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/tauffer-consulting/domino-airflow-pod-dev:gpu
          context: .
          file: Dockerfile-airflow-domino-pod-gpu

  domino-storage-sidecar:
    name: Domino Storage Sidecar Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Domino Storage Sidecar image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/tauffer-consulting/domino-shared-storage-sidecar-dev:latest
          context: domino/custom_operators/sidecar
          file: domino/custom_operators/sidecar/Dockerfile
